/*
Aeiou is protected by Aeiou Public License Version 1.
Made by kmc7468
*/

#ifndef AEIOU_HEADER_PREPROCESSOR_FEATURES_SUPPORTED_HH
#define AEIOU_HEADER_PREPROCESSOR_FEATURES_SUPPORTED_HH
#include <Aeiou/Configurations.hh>

#if AEIOU_CONFIG_SUPPORTED_FINAL == AEIOU_CONFIG_YES
#define AEIOU_SUPPORTED_FINAL
#endif

#if AEIOU_CONFIG_SUPPORTED_DELETE == AEIOU_CONFIG_YES
#define AEIOU_SUPPORTED_DELETE
#endif

#if AEIOU_CONFIG_SUPPORTED_NOEXCEPT == AEIOU_CONFIG_YES
#define AEIOU_SUPPORTED_NOEXCEPT
#endif

#if AEIOU_CONFIG_SUPPORTED_STATICASSERT == AEIOU_CONFIG_YES
#define AEIOU_SUPPORTED_STATIC_ASSERT
#endif

#endif