/*
Aeiou is protected by Aeiou Public License Version 1.
Made by kmc7468
*/

#ifndef AEIOU_HEADER_PREPROCESSOR_CONFIGURATIONS_DATALIMIT_VALUES_HH
#define AEIOU_HEADER_PREPROCESSOR_CONFIGURATIONS_DATALIMIT_VALUES_HH

#define AEIOU_CONFIG_PP_1BYTE (201000000L)
#define AEIOU_CONFIG_PP_2BYTE (201000001L)

#endif