/*
Aeiou is protected by Aeiou Public License Version 1.
Made by kmc7468
*/

#ifndef AEIOU_HEADER_CONFIGURATIONS_LINKINGMODE_VALUES_HH
#define AEIOU_HEADER_CONFIGURATIONS_LINKINGMODE_VALUES_HH

#define AEIOU_CONFIG_STATIC	(102000000L)
#define AEIOU_CONFIG_SHARED	(102000001L)
#define AEIOU_CONFIG_DYNAMIC AEIOU_CONFIG_SHARED

#endif